//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package books;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the books package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Books_QNAME = new QName("urn:books", "books");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: books
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BooksForm }
     * 
     * @return
     *     the new instance of {@link BooksForm }
     */
    public BooksForm createBooksForm() {
        return new BooksForm();
    }

    /**
     * Create an instance of {@link BookForm }
     * 
     * @return
     *     the new instance of {@link BookForm }
     */
    public BookForm createBookForm() {
        return new BookForm();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooksForm }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BooksForm }{@code >}
     */
    @XmlElementDecl(namespace = "urn:books", name = "books")
    public JAXBElement<BooksForm> createBooks(BooksForm value) {
        return new JAXBElement<>(_Books_QNAME, BooksForm.class, null, value);
    }

}
